title: Swift by Example
description: >
  Reference for common things in Swift, on Linux.
baseurl: ""
url: "https://willhbr.net/swift-by-example"

swift_version: 4.2

# Build settings
markdown: kramdown
highlighter: rouge
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
